# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    versioning-strategy: 'lockfile-only'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '05:00'
    commit-message:
      prefix: chore
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'increase'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '05:00'
    commit-message:
      prefix: chore
      include: 'scope'
