default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cherry_development

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'cherry_test' %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  database: cherry_production
  username: cherry
  password: <%= ENV["CHERRY_DATABASE_PASSWORD"] %>
