default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'postgres') %>

development:
  <<: *default
  database: cherry_development

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'cherry_test' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'cherry_production' %>
  username: <%= ENV['POSTGRES_USER'] || 'cherry' %>
  password: <%= ENV["POSTGRES_PASSWORD"] || ENV["CHERRY_DATABASE_PASSWORD"] %>
