name: Prevent new occurrences of JS lines of code

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  cherry_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          npm ci
          npm i -g cherrypush

      - name: Raise if new JS code added
        run: |
          cherry diff --quiet --metric "TODO/FIXME" --metric "[TS Migration] JS loc" --api-key ${{ secrets.CHERRY_API_KEY }} --error-if-increase
