name: cherry push

on:
  push:
    branches:
      - main

jobs:
  cherry:
    name: cherry push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          gem install rubocop
          npm i -g cherrypush
      - name: Push metrics
        run: cherry push --api-key=${{ secrets.CHERRY_API_KEY }}
