name: Push metrics to Cherry

on:
  push:
    branches:
      - main
      - show-diffs-on-cherry-diff

jobs:
  cherry:
    name: Push metrics to Cherry
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          npm install
          npm i ./cli

      - name: Push metrics to Cherry
        run: ./cli/bin/cherry.js push --api-key=${{ secrets.CHERRY_API_KEY }}
