name: cherry push

on:
  push:
    branches:
      - cherry
      - master

jobs:
  cherry:
    name: cherry push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install cherry
        run: npm i -g cherrypush
      - name: Push metrics
        run: cherry push --api-key=${{ secrets.CHERRY_API_KEY }}
