name: cherry diff

on:
  pull_request:

jobs:
  cherry:
    name: runner / cherry
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Install dependencies
        run: |
          bundle install
          npm i -g cherrypush

      - name: Cherry diff
        run: cherry diff origin/${{ github.base_ref }}
