name: cherry diff

on:
  pull_request:

jobs:
  cherry:
    name: runner / cherry
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          gem install rubocop
          npm i -g cherrypush
      - name: Cherry diff
        run: cherry diff origin/${{ github.base_ref }}
