name: Track codebase stats

on:
  push:
    branches:
      - main

jobs:
  cherry_push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          npm ci
          npm i -g cherrypush

      - name: Push metrics to Cherry
        run: cherry push --api-key=${{ secrets.CHERRY_API_KEY }}
