name: cherry diff

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  cherry_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetches all commits from all branches
          ref: ${{ github.head_ref }} # checks out the branch that triggered the workflow

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          npm ci
          npm i -g cherrypush

      - name: Raise if new JS code added
        run: |
          cherry diff --quiet --metric "TODO/FIXME" --metric "[TS Migration] JS loc" --api-key ${{ secrets.CHERRY_API_KEY }} --error-if-increase
